cou <- read.table("F:/KG/per/coursera/explor/exdata-data-household_power_consumption/household_power_consumption.txt",sep=";",head=TRUE)

cou$datetim <- paste(cou$Date,cou$Time)
cou$datetim1 <- strptime(cou$datetim,"%d/%m/%Y %H:%M:%S")
cou$Date1 <- as.Date(cou$Date,'%d/%m/%Y')
cou1 <- cou[cou$Date1 == '2007-02-01' | cou$Date1 == '2007-02-02' ,]
cou1$Global_active_power1 <- as.numeric(as.character(cou1$Global_active_power))
cou1$Voltage <- as.numeric(as.character(cou1$Voltage))

png(filename="F:/KG/per/coursera/explor/exdata-data-household_power_consumption/plot4.png",width=480,height=480)
par(mar=c(2,4,1,1))
par(mfrow=c(2,2))
plot(cou1$datetim1,cou1$Global_active_power1,type="l",xlab="",ylab="Global Active Power")
plot(cou1$datetim1,cou1$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(cou1$datetim1,cou1$Sub_metering_1,type="l",col="black",ylab="Energy sub metering",xlab="")
lines(cou1$datetim1,cou1$Sub_metering_2,type="l",col="red")
lines(cou1$datetim1,cou1$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1))
plot(cou1$datetim1,cou1$Global_reactive_power,type="l",xlab="",ylab="Global Active Power")
dev.off()
